-- Extend properties with amenities + extra listing details

alter table public.properties
  add column if not exists balconies int,
  add column if not exists water_supply text,
  add column if not exists pet_allowed smallint,
  add column if not exists gym smallint,
  add column if not exists non_veg_allowed smallint,
  add column if not exists gated_security smallint,
  add column if not exists who_will_show_property text,
  add column if not exists current_property_condition text,
  add column if not exists secondary_phone text,
  add column if not exists more_similar_units_available smallint,
  add column if not exists direction_tip text,
  add column if not exists amenity_lift smallint,
  add column if not exists amenity_internet_services smallint,
  add column if not exists amenity_air_conditioner smallint,
  add column if not exists amenity_club_house smallint,
  add column if not exists amenity_intercom smallint,
  add column if not exists amenity_swimming_pool smallint,
  add column if not exists amenity_children_play_area smallint,
  add column if not exists amenity_fire_safety smallint,
  add column if not exists amenity_servant_room smallint,
  add column if not exists amenity_shopping_center smallint,
  add column if not exists amenity_gas_pipeline smallint,
  add column if not exists amenity_park smallint,
  add column if not exists amenity_rain_water_harvesting smallint,
  add column if not exists amenity_sewage_treatment_plant smallint,
  add column if not exists amenity_house_keeping smallint,
  add column if not exists amenity_power_backup smallint,
  add column if not exists amenity_visitor_parking smallint;
